# https://github.com/uber/AutoDispose/blob/master/.github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  BuildTest:
    name: Build and test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew cAT --continue
          api: 28
          tag: default
          abi: x86
          cmdOptions: -noaudio -no-boot-anim -no-window
      - name: Archive Espresso results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Logcat-Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: Save logcat output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Logcat-logcat
          path: artifacts/logcat.log
      - name: png-find
        run: find screenshots -name '*.png'
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Logcat-Screenshots
          path: screenshots/adb
      - name: cleanup
        run: ./signing/cleanup.sh
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: gradle check
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Logcat-Lint-report
          path: ./**/build/reports/lint-results*.html
