# https://github.com/uber/AutoDispose/blob/master/.github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  BuildTest:
    name: Build and test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.0.7.5
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.0.7.5
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v2.2.0
        if: ${{ always() }}
        with:
          name: Logcat-Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logcat-logcat
          path: artifacts/logcat.log
      - name: png-find
        run: find screenshots -name '*.png'
      - name: Archive screenshots
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Logcat-Screenshots
          path: screenshots/adb
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: gradle check
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.2.0
        if: ${{ always() }}
        with:
          name: Logcat-Lint-report
          path: sample/build/reports/lint-results.html
