# https://github.com/uber/AutoDispose/blob/master/.github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  BuildTest:
    name: Test ${{ matrix.os }} ${{ matrix.abi }} ${{ matrix.api }} ${{ matrix.tag }} java ${{ matrix.java_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 17 ]
        os:  [ macos-14-xlarge ]
        api: [ 31 ]
        abi: [ arm64-v8a ]
        tag: [ 'google_apis' ]
#        include:
#          - java_version: 17
#            os: macOS-14
#            api: 31
#            abi: arm64-v8a
#            tag: 'google_apis'
    steps:
      - name: Show architecture
        run: uname -a
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - uses: gradle/wrapper-validation-action@v3
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.4.10
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.1.4.10
        with:
          cmd: ./gradlew cAT --continue
          api: ${{ matrix.api }}
          tag: ${{ matrix.tag }}
          abi: ${{ matrix.abi }}
          cmdOptions: -noaudio -no-boot-anim -no-window -metrics-collection
          bootTimeout: 720 # seconds = 12 minutes
      - name: Archive Espresso results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Logcat-Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Logcat-Screenshots
          path: |
            sample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            sample/build/outputs/androidTest-results/connected
      - name: cleanup
        run: ./signing/cleanup.sh
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: gradle check
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Logcat-Lint-report
          path: ./**/build/reports/lint-results*.html
